CREATE TABLE IF NOT EXISTS EDU_ESD_QSTN (
	ESD_QSTN_SN INT NOT NULL AUTO_INCREMENT COMMENT '지속가능발전교육문항순번',
	QSTN_TYPE_CD VARCHAR(20) NOT NULL COMMENT '질문유형코드(OX, SELECT)',
	QSTN_CN TEXT NOT NULL COMMENT '질문내용',
	QSTN_IMG_ATCH_FILE_ID VARCHAR(20) NULL COMMENT '질문이미지첨부파일ID',
	OPTN_CN LONGTEXT NOT NULL COMMENT '보기내용(JSON 배열)',
	CRANS_NO VARCHAR(20) NOT NULL COMMENT '정답번호(1부터 시작)',
	CRANS_EXPLN TEXT NULL COMMENT '정답설명',
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	SORT_SEQ INT NOT NULL DEFAULT 0 COMMENT '정렬순서',
	REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	RGTR_NM VARCHAR(100) NULL DEFAULT 'system' COMMENT '등록자명',
	MDFCN_DT DATETIME NULL COMMENT '수정일시',
	MDFR_NM VARCHAR(100) NULL COMMENT '수정자명',
	DEL_DT DATETIME NULL COMMENT '삭제일시',
	DLTR_NM VARCHAR(100) NULL COMMENT '삭제자명',
	PRIMARY KEY (ESD_QSTN_SN),
	KEY IDX_EDU_ESD_QSTN_01 (USE_YN, SORT_SEQ, ESD_QSTN_SN),
	KEY IDX_EDU_ESD_QSTN_02 (DEL_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='지속가능발전교육문제은행';

INSERT INTO CMMN_CD_DTL (
	CD_ID,
	CD_DTL_ID,
	CD_DTL_NM,
	CD_DTL_CN,
	SORT_SEQ,
	USE_YN,
	ETC1,
	ETC2,
	ETC3,
	ATCH_FILE_MNG_NO,
	RGTR_NM,
	REG_DT
) VALUES (
	'COM002',
	'3006',
	'문제은행',
	'/admin/esd-question-bank',
	60,
	'Y',
	'',
	'/admin/esd-question-bank',
	'/admin/esd-question-bank',
	'',
	'admin',
	NOW()
) ON DUPLICATE KEY UPDATE
	CD_DTL_NM = VALUES(CD_DTL_NM),
	CD_DTL_CN = VALUES(CD_DTL_CN),
	SORT_SEQ = VALUES(SORT_SEQ),
	USE_YN = VALUES(USE_YN),
	ETC2 = VALUES(ETC2),
	ETC3 = VALUES(ETC3);

INSERT INTO AUTH_MENU_MAP (AUTHRT_CD, MENU_CD, RGTR_NM, REG_DT)
SELECT DISTINCT SOURCE_MAP.AUTHRT_CD, '3006', 'admin', NOW()
FROM AUTH_MENU_MAP SOURCE_MAP
WHERE SOURCE_MAP.MENU_CD = '3002'
AND NOT EXISTS (
	SELECT 1
	FROM AUTH_MENU_MAP TARGET_MAP
	WHERE TARGET_MAP.AUTHRT_CD = SOURCE_MAP.AUTHRT_CD
	AND TARGET_MAP.MENU_CD = '3006'
);
