CREATE TABLE IF NOT EXISTS EDU_LRN_MTRL_DWNLD_LOG (
	DWNLD_SN BIGINT NOT NULL AUTO_INCREMENT COMMENT '다운로드일련번호',
	PST_SN VARCHAR(20) NOT NULL COMMENT '게시물일련번호',
	ATCH_FILE_MNG_NO VARCHAR(20) NULL COMMENT '첨부파일관리번호',
	FILE_SEQ INT NULL COMMENT '파일순서번호',
	DATA_TYPE_CD VARCHAR(20) NOT NULL COMMENT '자료유형코드',
	DWNLD_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '다운로드일시',
	RGTR_NM VARCHAR(100) NULL COMMENT '등록자명',
	PRIMARY KEY (DWNLD_SN),
	KEY IX_EDU_LRN_MTRL_DWNLD_PST_FILE (PST_SN, ATCH_FILE_MNG_NO, FILE_SEQ),
	KEY IX_EDU_LRN_MTRL_DWNLD_DT (DWNLD_DT)
) COMMENT='교육 학습자료 다운로드 로그';
