-- ULMFE 태블릿 FCM 기기 및 학생 연결 테이블
-- 실제 서비스 계정/FCM 토큰은 소스가 아니라 실행 환경에서 관리한다.

CREATE TABLE IF NOT EXISTS EDU_PUSH_DVC (
    DVC_ID VARCHAR(36) NOT NULL COMMENT '기기 식별자',
    FCM_TKN VARCHAR(2048) NULL COMMENT 'FCM 등록 토큰',
    ROLE_CD VARCHAR(20) NULL COMMENT '사용자 역할 코드',
    RSVT_SN INT NULL COMMENT '예약 일련번호',
    ACTV_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '활성 여부',
    CLNT_UPDT_DT DATETIME NULL COMMENT '클라이언트 수정 일시',
    LAST_UPDT_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    PRIMARY KEY (DVC_ID),
    KEY IX_EDU_PUSH_DVC_01 (RSVT_SN, ROLE_CD, ACTV_YN),
    CONSTRAINT FK_EDU_PUSH_DVC_01 FOREIGN KEY (RSVT_SN) REFERENCES EDU_RSVT_MST (RSVT_SN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='교육 푸시 기기';

CREATE TABLE IF NOT EXISTS EDU_PUSH_DVC_STDNT (
    DVC_ID VARCHAR(36) NOT NULL COMMENT '기기 식별자',
    RSVT_SN INT NOT NULL COMMENT '예약 일련번호',
    STDNT_SN INT NOT NULL COMMENT '학생 일련번호',
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    PRIMARY KEY (DVC_ID, STDNT_SN),
    KEY IX_EDU_PUSH_DVC_STDNT_01 (RSVT_SN, STDNT_SN),
    CONSTRAINT FK_EDU_PUSH_DVC_STDNT_01 FOREIGN KEY (DVC_ID) REFERENCES EDU_PUSH_DVC (DVC_ID) ON DELETE CASCADE,
    CONSTRAINT FK_EDU_PUSH_DVC_STDNT_02 FOREIGN KEY (RSVT_SN) REFERENCES EDU_RSVT_MST (RSVT_SN),
    CONSTRAINT FK_EDU_PUSH_DVC_STDNT_03 FOREIGN KEY (STDNT_SN) REFERENCES EDU_RSVT_STDNT (STDNT_SN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='교육 푸시 기기 학생';
